#!/usr/bin/env bash
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: run as root"
    exit 1
fi

WIREGUARD_SERVICE="/root/web/src/ui/services/wireguard_service.py"
WG_STATS="/root/web/src/wg_stats.py"
BACKUP_SUFFIX=".bak.wdtt0"
SYNC_SCRIPT="/usr/local/bin/wdtt0-sync-names.py"
CRON_FILE="/etc/cron.d/wdtt0-sync"
WG_CONF="/etc/wireguard/wdtt0.conf"

echo "[Wdtt0] Installing wdtt0 name sync for StatusOpenVPN..."

# 1. Backup original StatusOpenVPN files (only once)
if [ ! -f "${WIREGUARD_SERVICE}${BACKUP_SUFFIX}" ]; then
    cp "$WIREGUARD_SERVICE" "${WIREGUARD_SERVICE}${BACKUP_SUFFIX}"
    echo "[Wdtt0] Backed up $WIREGUARD_SERVICE"
fi
if [ ! -f "${WG_STATS}${BACKUP_SUFFIX}" ]; then
    cp "$WG_STATS" "${WG_STATS}${BACKUP_SUFFIX}"
    echo "[Wdtt0] Backed up $WG_STATS"
fi

# 2. Patch StatusOpenVPN to read /etc/wireguard/wdtt0.conf
python3 - <<'PY'
import sys
files = [
    "/root/web/src/ui/services/wireguard_service.py",
    "/root/web/src/wg_stats.py",
]
old = "    client_mapping = {**vpn_mapping, **antizapret_mapping}"
new = """    wdtt_mapping = read_wg_config('/etc/wireguard/wdtt0.conf')
    client_mapping = {**vpn_mapping, **antizapret_mapping, **wdtt_mapping}"""
for path in files:
    with open(path, "r", encoding="utf-8") as f:
        s = f.read()
    if "wdtt_mapping" in s:
        print(f"[Wdtt0] {path} already patched, skipping")
        continue
    if old not in s:
        print(f"[Wdtt0] WARNING: pattern not found in {path}", file=sys.stderr)
        sys.exit(1)
    s = s.replace(old, new, 1)
    with open(path, "w", encoding="utf-8") as f:
        f.write(s)
    print(f"[Wdtt0] Patched {path}")
PY

# 3. Create sync script
cat > "$SYNC_SCRIPT" <<'PY'
#!/usr/bin/env python3
import json
import os
import subprocess
import sys

CONFIG_DIR = "/etc/wdtt"
WG_CONF_PATH = "/etc/wireguard/wdtt0.conf"
KEYS_FILE = "/etc/wdtt/wg-keys.dat"


def run(cmd):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True)


def main():
    db_path = os.path.join(CONFIG_DIR, "passwords.json")
    if not os.path.exists(db_path):
        print(f"[Wdtt0-sync] DB not found: {db_path}")
        sys.exit(0)

    with open(db_path, "r", encoding="utf-8") as f:
        db = json.load(f)

    devices = db.get("devices", {})
    passwords = db.get("passwords", {})

    # device_id -> (label, linked_to_password)
    dev_to_label = {}
    dev_linked = {}
    for dev_id in devices:
        label = "N/A"
        linked = False
        for password, entry in passwords.items():
            if not entry:
                continue
            ids = list(entry.get("device_ids") or [])
            entry_dev_id = entry.get("device_id")
            if entry_dev_id and entry_dev_id not in ids:
                ids.insert(0, entry_dev_id)
            if dev_id in ids:
                label = entry.get("label") or password
                linked = True
                break
        dev_to_label[dev_id] = label
        dev_linked[dev_id] = linked

    # Read current peers from wg, skip orphan devices (not linked to any password)
    peers = []
    skipped = 0
    res = run("wg show wdtt0 allowed-ips")
    for line in res.stdout.strip().splitlines():
        parts = line.split()
        if len(parts) < 2:
            continue
        pubkey = parts[0].strip()
        allowed_ip = parts[1].strip()
        ip = allowed_ip.split("/")[0]
        dev_id = None
        for did, dev in devices.items():
            if dev.get("ip") == ip:
                dev_id = did
                break
        if not dev_id or not dev_linked.get(dev_id, False):
            print(f"[Wdtt0-sync] Skipping orphan peer {pubkey[:20]}... ({allowed_ip})")
            skipped += 1
            continue
        label = dev_to_label[dev_id]
        peers.append((label, pubkey, allowed_ip))

    # Interface info
    listen_port = run("wg show wdtt0 listen-port").stdout.strip() or "56001"
    server_private = ""
    if os.path.exists(KEYS_FILE):
        with open(KEYS_FILE, "r", encoding="utf-8") as f:
            lines = [l.strip() for l in f.readlines() if l.strip()]
            if lines:
                server_private = lines[0]

    lines = [
        "# Auto-generated by wdtt0-sync-names.py",
        "# DO NOT EDIT MANUALLY",
        "[Interface]",
    ]
    if server_private:
        lines.append(f"PrivateKey = {server_private}")
    lines.append("Address = 10.66.66.1/16")
    lines.append(f"ListenPort = {listen_port}")
    lines.append("")

    for label, pubkey, allowed_ip in peers:
        lines.append(f"# Client = {label}")
        lines.append("[Peer]")
        lines.append(f"PublicKey = {pubkey}")
        lines.append(f"AllowedIPs = {allowed_ip}")
        lines.append("")

    os.makedirs(os.path.dirname(WG_CONF_PATH), exist_ok=True, mode=0o700)
    tmp = WG_CONF_PATH + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    os.chmod(tmp, 0o600)
    os.replace(tmp, WG_CONF_PATH)
    print(f"[Wdtt0-sync] Updated {WG_CONF_PATH} with {len(peers)} peers (skipped {skipped} orphan)")


if __name__ == "__main__":
    main()
PY

chmod +x "$SYNC_SCRIPT"
echo "[Wdtt0] Created $SYNC_SCRIPT"

# 4. Add cron job
printf '* * * * * root %s >> /var/log/wdtt0-sync.log 2>&1\n' "$SYNC_SCRIPT" > "$CRON_FILE"
chmod 644 "$CRON_FILE"
echo "[Wdtt0] Added cron job $CRON_FILE"

# 5. Run sync once immediately
$SYNC_SCRIPT

# 6. Restart StatusOpenVPN
systemctl restart StatusOpenVPN

echo "[Wdtt0] Done. StatusOpenVPN restarted."
echo "[Wdtt0] Names for wdtt0 will update every minute from Telegram labels."
